# Generated by Django 5.0 on 2023-12-07 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=300)),
                ('book_isbn', models.IntegerField(max_length=13)),
                ('book_author', models.CharField(max_length=100)),
                ('book_year_of_publication', models.CharField(max_length=4)),
                ('book_genre', models.CharField(max_length=300)),
                ('book_availability', models.BooleanField(default=True)),
                ('book_delete_status', models.BooleanField(default=False)),
            ],
        ),
    ]
