# Generated by Django 5.0 on 2023-12-07 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklist',
            name='book_isbn',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='booklist',
            name='book_year_of_publication',
            field=models.IntegerField(),
        ),
    ]
