# Generated by Django 5.0 on 2023-12-10 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_booklist_book_isbn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booklist',
            old_name='book_isbn',
            new_name='book_isbn_13',
        ),
    ]
